import Navbar from '@/components/navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=" m-auto mt-4">

      <Navbar/>
        <div className='container m-auto'>{children}</div>
      </body>
    </html>
  )
}
